[package]
name = "egui_infinite_scroll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
egui_extras = ["dep:egui_extras"]

[dependencies]
egui_inbox = { path = "../egui_inbox" }

egui = { version = "0.22.0", default-features = false }
egui_extras = { version = "0.22.0", default-features = false, optional = true }

[dev-dependencies]
eframe = "0.22.0"

