[package]
name = "egui_infinite_scroll"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
egui_extras = ["dep:egui_extras"]

[[example]]
name = "infinite_scroll_table"
required-features = ["egui_extras"]


[dependencies]
egui_inbox = { path = "../egui_inbox" }
egui_virtual_list = { path = "../egui_virtual_list" }

egui.workspace = true
egui_extras = { workspace = true, optional = true }
web-time = "0.2"

[dev-dependencies]
eframe = { workspace = true, default-features = true }
rand = "0.8"