[package]
name = "fancy-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
egui_dnd = { path = "../crates/egui_dnd" }
egui_infinite_scroll = { path = "../crates/egui_infinite_scroll" }
hello_egui_utils = { path = "../crates/hello_egui_utils" }
egui_inbox = { path = "../crates/egui_inbox" }
egui_animation = { path = "../crates/egui_animation" }
egui_thumbhash = { path = "../crates/egui_thumbhash" }

egui = { workspace = true, features = ["color-hex"] }
eframe = { workspace = true, default-features = true }
egui_extras = { workspace = true, features = ["http", "image"] }
ehttp = { version = "0.3.0" }
thumbhash = "0.1.0"

image = { version = "0.24", features = ["jpeg", "png", "webp"] }
color-hex = "0.2.0"

wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["time", "rt", "macros"] }
ureq = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.39"
gloo-timers = { version = "0.3.0", features = ["futures"] }

[package.metadata.release]
release = false
