[package]
name = "fancy-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
egui_dnd = { path = "../crates/egui_dnd" }
egui_infinite_scroll = { path = "../crates/egui_infinite_scroll" }

egui = { workspace = true, features = ["color-hex"] }
eframe = { workspace = true, default-features = true }
egui_extras = { workspace = true, features = ["http", "image"] }
ehttp = { version = "0.3.0" }

image = { version = "0.24", features = ["jpeg", "png"] }
color-hex = "0.2.0"

wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

[package.metadata.release]
release = false
