
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["fancy-example", "crates/*"]
resolver = "2"

[workspace.dependencies]
egui_dnd = { path = "./crates/egui_dnd", version = "0.5.1" }
egui_animation = { path = "./crates/egui_animation", version = "0.1.0" }
hello_egui_utils = { path = "./crates/hello_egui_utils", version = "0.1.0" }
egui_inbox = { path = "./crates/egui_inbox", version = "0.1.1" }

egui = { version = ">=0.22", default-features = false }
eframe = { version = ">=0.22", default-features = false }
egui_extras = { version = ">=0.22", default-features = false }

[patch.crates-io]
taffy = { git = "https://github.com/DioxusLabs/taffy", branch = "main" }
