
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["fancy-example", "crates/*"]

[workspace.dependencies]
egui = { version = ">=0.22", default-features = false }
eframe = { version = ">=0.22", default-features = false }
egui_extras = { version = ">=0.22", default-features = false }

[patch.crates-io]
taffy = { git = "https://github.com/nicoburns/taffy", branch = "measure-func-context" }
