
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["fancy-example", "crates/*"]

[patch.crates-io]
taffy = { git = "https://github.com/nicoburns/taffy", branch = "measure-func-context" }
