[package]
name = "egui_webview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "0.35.0"
egui.workspace = true
egui_inbox = { path = "../egui_inbox" }

image = "0.24.8"
base64 = "0.21.7"
egui_extras = { version = "0.25.0", features = ["image",] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1"
log = "0.4.20"
rgb = "0.8"

[dev-dependencies]
eframe = { workspace = true, default-features = true }
