[package]
name = "egui_webview"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.release]
release = false

[dependencies]
wry = "0.45.0"
egui.workspace = true
egui_inbox = { workspace = true }

image = "0.25.2"
base64 = "0.22.1"
egui_extras = { workspace = true, features = ["image"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1"
log = "0.4.22"
rgb = "0.8"

[dev-dependencies]
eframe = { workspace = true, default-features = true }

[lints]
workspace = true
