[package]
name = "egui_webview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "0.35.0"
egui.workspace = true
egui_inbox = { path = "../egui_inbox" }

[dev-dependencies]
eframe = { workspace = true, default-features = true }
