[package]
name = "egui_taffy"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.release]
release = false

[dependencies]
egui.workspace = true

taffy = "0.4.0"

[dev-dependencies]
eframe = {workspace = true, default-features = true}

rand = "0.8.5"

