name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: libsoup-3.0-0
          version: 1.0
          execute_install_scripts: true

      - uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Clippy all-features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --workspace -- -D warnings

      - name: RustFmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace

      - name: Cargo Doc
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --lib --no-deps --all-features

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Miri
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: miri

      # Separate miri setup from run so that 'Miri Test'
      # logs are clean.
      - name: Setup Miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: setup

      - name: Miri Test
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test --all-features
